# 这个文件应该存储在Nacos配置中心
# Data ID: user-service-dev.yaml
# Group: DEFAULT_GROUP

# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mall_user}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ENC(${DB_PASSWORD_ENCRYPTED})  # 加密的密码
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mall.*.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    qos-port: 22222
  registry:
    address: nacos://${NACOS_SERVER_ADDR:localhost:8848}
    parameters:
      namespace: ${NACOS_NAMESPACE:dev}
      group: DUBBO_GROUP
  protocol:
    name: dubbo
    port: ${DUBBO_PORT:20880}
    threads: 200
  consumer:
    check: false
    timeout: 30000
    retries: 2
  provider:
    timeout: 30000
    retries: 2
    threads: 200

# 业务配置
app:
  config:
    jwt:
      secret: ${JWT_SECRET:mall@2024SecretKey!}
      expiration: 7200  # 2小时
      refresh-expiration: 604800  # 7天
    sms:
      enabled: true
      provider: aliyun
      access-key: ${SMS_ACCESS_KEY}
      secret-key: ENC(${SMS_SECRET_KEY_ENCRYPTED})
    oss:
      enabled: true
      type: minio
      endpoint: ${OSS_ENDPOINT:http://localhost:9000}
      bucket: ${OSS_BUCKET:mall}
      access-key: ${OSS_ACCESS_KEY}
      secret-key: ENC(${OSS_SECRET_KEY_ENCRYPTED})