server:
  port: 8080

spring:
  application:
    name: mall-gateway
  config:
    import:
      - "optional:nacos:mall-gateway.yml?group=DEFAULT_GROUP"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: DEFAULT_GROUP

    sentinel:
      transport:
        dashboard: localhost:8858

  data:
    redis:
      database: 0
      port: 6379
      host: localhost
      password:

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露Actuator的监控端点
  endpoint:
    health:
      show-details: always #显示健康的详细信息
    env:
      show-values: always #默认Actuator的环境变量会以****显示，这里开启显示
    configprops:
      show-values: always #默认Actuator的配置属性会以****显示，这里开启显示
    info:
      enabled: true
knife4j:
  gateway:
    enabled: true
    strategy: discover #网关文档聚合方式：服务发现（自动聚合）
    discover:
      version: openapi3 #配置OpenAPI3规范
      enabled: true #配置开启服务发现
      excluded-services: mall-monitor #排除监控服务
    tags-sorter: order #配置tag排序规则
    operations-sorter: order #配置operation排序规则
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-header: true
  # token前缀
  token-prefix: Bearer
  # 是否打印banner
  is-print: false

