spring:
  cloud:
    gateway:
      routes:
        - id: seckill-service
          uri: lb://seckill-service
          order: 0
          predicates:
            - name: Path
              args:
                pattern: /api/seckill/**
            - name: Between
              args:
                datetime1: "2024-01-01T00:00:00+08:00[Asia/Shanghai]"
                datetime2: "2024-12-31T23:59:59+08:00[Asia/Shanghai]"
          filters:
            - name: StripPrefix
              args:
                parts: 2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
                deny-empty-key: true
                empty-key-status-code: 403
          metadata:
            description: "秒杀服务路由，严格限流"

        - id: product-service
          uri: lb://product-service
          order: 1
          predicates:
            - name: Path
              args:
                pattern: /api/product/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                key-resolver: "#{@ipKeyResolver}"

        - id: order-service
          uri: lb://order-service
          order: 2
          predicates:
            - name: Path
              args:
                pattern: /api/order/**

        - id: user-service
          uri: lb://user-service
          order: 3
          predicates:
            - name: Path
              args:
                pattern: /api/user/**
