# MyBatis-Plus configuration for application.yml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # Master data source
      master:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}

      # Slave data source (for read-only)
      slave:
        enabled: false  # Enable for read/write separation
        url: jdbc:mysql://${DB_SLAVE_HOST:localhost}:${DB_SLAVE_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: ${DB_SLAVE_USERNAME:root}
        password: ${DB_SLAVE_PASSWORD:root}

      # Connection pool configuration
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      # Filters
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # Monitoring configuration
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        reset-enable: false
        allow: ""  # Allow all IPs
        deny: ""   # Deny none

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name: USER_SESSION
        principal-cookie-name: USER_COOKIE
        profile-enable: true

# MyBatis-Plus configuration
mybatis-plus:
  # Mapper XML locations
  mapper-locations: classpath*:/mapper/**/*.xml
  # Entity package
  type-aliases-package: com.mall.**.entity

  # Global configuration
  global-config:
    # Database configuration
    db-config:
      # Primary key type: ASSIGN_ID (Snowflake algorithm)
      id-type: ASSIGN_ID
      # Table name mapping: camelCase to underscore
      table-underline: true
      # Capital mode
      capital-mode: false
      # Logical delete configuration
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # Insert strategy
      insert-strategy: NOT_NULL
      # Update strategy
      update-strategy: NOT_NULL
      # Select strategy
      where-strategy: NOT_NULL

    # Print banner
    banner: false

  # Configuration
  configuration:
    # Enable camelCase to underscore mapping
    map-underscore-to-camel-case: true
    # Disable caching
    cache-enabled: false
    # JDBC type for null
    jdbc-type-for-null: NULL
    # Call setters on null values
    call-setters-on-nulls: true
    # Return null when all columns are NULL
    return-instance-for-empty-row: false
    # Log implementation (remove in production)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # Lazy loading
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    # Multiple result sets
    multiple-result-sets-enabled: true
    # Use column label
    use-column-label: true
    # Use generated keys
    use-generated-keys: true
    # Auto mapping behavior
    auto-mapping-behavior: PARTIAL
    # Auto mapping unknown column behavior
    auto-mapping-unknown-column-behavior: WARNING
    # Default executor type
    default-executor-type: SIMPLE
    # Default statement timeout (seconds)
    default-statement-timeout: 30
    # Default fetch size
    default-fetch-size: 100
    # Safe row bounds enabled
    safe-row-bounds-enabled: false